name: Actions Workflow

on:
    push:
      #branches-ignore:
      #  - null
      branches:
        - master
        - 'feature/*' # matchers feature/b1 feature/b2 ....
      #  - 'feature/**' # matchers feature/b1/* feature/b2/* ....
      #  - '!feature/**' # ignore branch ....
      # tags:
      #  - 'v1.*'
      # paths:
      #  - '**.js' # only if in commit we find js files
      #  - '!filename.js' #ignore
      # paths-ignore:
      #  - 'docs/**'
    #[push, pull_request]
    # push:
    # pull_request:
    #  types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mikhail Devyatov'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
