name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - uses: actions/checkout@v1
      - name: Log node version
        with:
          entrypoint: ./script.sh
          args: "Hi!"
